<?php

return [
    // Limit the number of displayed toasts
    'maxItems' => null,

    'options' => [
        'closeButton' => true,
        'closeClass' => 'toast-close-button',
        'closeHtml' => '<button><i class="icon-off"></i></button>',
        'closeDuration' => 300,
        'closeEasing' => 'swing',
        'closeMethod' => 'fadeOut',
        'closeOnHover' => true,
        'containerId' => 'toast-container',
        'debug' => false,
        'escapeHtml' => false,
        'extendedTimeOut' => 10000,
        'hideDuration' => 1000,
        'hideEasing' => 'linear',
        'hideMethod' => 'fadeOut',
        'iconClass' => 'toast-info',
        'iconClasses' => [
            'error' => 'toast-error',
            'info' => 'toast-info',
            'success' => 'toast-success',
            'warning' => 'toast-warning',
        ],
        'messageClass' => 'toast-message',
        'newestOnTop' => false,
        'onHidden' => null,
        'onShown' => null,
        'positionClass' => 'toast-top-right',
        'preventDuplicates' => false,
        'progressBar' => true,
        'progressClass' => 'toast-progress',
        'rtl' => false,
        'showDuration' => 300,
        'showEasing' => 'swing',
        'showMethod' => 'fadeIn',
        'tapToDismiss' => false,
        'target' => 'body',
        'timeOut' => 10000,
        'titleClass' => 'toast-title',
        'toastClass' => 'toast',
    ],
];
